#!/usr/bin/env bash
# while loop/if statements
x=0
while ((x < 10))
do
		if [[ $x == 7 ]]; then
		      	echo "good luck"
		elif [[ $x == 3 ]]; then
			echo "bad luck"
		else
			echo "Holberton School"
		fi
		((x += 1))
done