#!/usr/bin/env bash
# case statement
x=1
while ((x < 21))
do
		case $x in
			4)
				echo $x
				echo "bad luck from China"
				;;
			9)
				echo $x
				echo "bad luck from Japan"
				;;
			17)
				echo $x
				echo "bad luck from Italy"
				;;
			*)
				echo $x
				;;
		esac
		((x += 1))
done
